### ISSUE TITLE
Optionals not working with "String" - but they do with "NSString"

### ISSUE THREAD

**Issue by marbetschar** [SocialbitGmbH/SwiftAddressBook#21] opened 2015-03-08 20:50 UTC
I've noticed the following statement crashes my app under certain cirumstances:

    if let firstName = addressBookPerson.firstName{
        ...
    }

However, if I change the underlying getter method for "firstName" to use "NSString?" instead of "String?" everything works like a charm:

    public var firstName : NSString? {
        get {
            return extractProperty(kABPersonFirstNameProperty)
        }
        set {
            setSingleValueProperty(kABPersonFirstNameProperty, NSString(optionalString: newValue))
        }
    }

As a result I've changed the type of all "String?" to "NSString?" in the SwiftAddressBookWrapper :(
Any idea why this happens?

**Comment by TAKeanice** [comment] 2015-03-08 22:23
Here is what should happen: toll-free bridging converts the CFStringRef to an NSString, which is then converted to a Swift String!

**Comment by TAKeanice** [comment] 2015-03-08 22:25
Which is equal to a String? but can be used like String, because it's implicitly unwrapped, and can crash at runtime. To avoid this, the return type was declared as String?

**Comment by TAKeanice** [comment] 2015-03-08 22:27
Now, either I have made some mistake in above statements, our the swift compiler or the objective-c runtime is getting mad at some point

**Comment by marbetschar** [comment] 2015-03-08 23:48
I have no clue why it's not working with a regular Swift String. But I've seen rumors of others claiming about "String" to be not working correctly when used with the AddressBook - unfortunately I can't find the StackOverflow post again right now :(

**Comment by TAKeanice** [comment] 2015-03-09 22:16
There are some posts about unwrapping unsafe pointers in Swift, which were written back in the first betas of XCode 6, where you had to use an ugly workaround for using them. Those problems have been fixed in the release version, though

**Comment by TAKeanice** [comment] 2015-03-13 08:10
@marbetschar I´ve added one test to check for nil failures and unwrapping failures in bea5dc70d920d715a251937eede79108c16c24f0 . Feel free to add the case where your code is crashing, so that I can reproduce and fix it!

**Comment by marbetschar** [comment] 2015-03-13 22:57
Ok cool, seems to working now! :)

**Closed** 2015-03-14 13:24 UTC
