### ISSUE TITLE
Gives me an error

### ISSUE THREAD

**Issue by hitec** [SocialbitGmbH/SwiftAddressBook#40] opened 2015-06-08 20:13 UTC
As far as I can tell, the pod is installed correctly. I am facing an issue when ever I try to import "SwiftAddressBook"  it tells me No such module exist

**Comment by TAKeanice** [comment] 2015-06-10 13:11
Have you tested the sample application? There, it is done exactly this way.

**Comment by joubin** [comment] 2015-06-21 06:06
I am having the same issue. I made a video. Maybe that'll help you see what Im seeing.

https://www.youtube.com/watch?v=1WZQvo5-KHA

**Comment by TAKeanice** [comment] 2015-06-23 14:57
Sorry, seems like I have not maintained the pod properly. The version the pod was on was still no Swift 1.2... Now, a new pod version was pushed. Please test again with this. I will close this issue, since I could reproduce it now and it was solved for me through my last test.

**Comment by TAKeanice** [comment] 2015-06-23 14:58
Use `pod update` to get version 0.4.3

**Closed by TAKeanice** 2015-06-23 14:57 UTC

**Comment by TAKeanice** [comment] 2015-09-08 18:29
I ran into the same issue again today. Solved by moving to a folder without special symbols.

**Comment by danielkiedrowski** [comment] 2016-08-09 13:24
Running in this error again. Using 0.6.2, Cocoapods 1.0.1, XCode 7.3.1
