### ISSUE TITLE
EXC_BAD_ACCESS in convertRecordsToPersons

### ISSUE THREAD

**Issue by samuelbeek** [SocialbitGmbH/SwiftAddressBook#37] opened 2015-05-22 08:16 UTC
In the return of this function I get a EXC_BAD_ACCES

    public var allPeople : [SwiftAddressBookPerson]? {
        get {
            return convertRecordsToPersons(ABAddressBookCopyArrayOfAllPeople(internalAddressBook).takeRetainedValue())
        }
    }

This happens on *some* devices when calling this function (Yes, I have access)
 
    if let people = swiftAddressBook?.allPeople {
        for person in people {
            println(person)
        }
    }

I use Swift 1.2 and the Swift_1.2_take2 brach. I have tried a few things to see what is causing this crash: I made address book records without first/last names, whiteout names at all, without phone numbers, but none of this seems to cause it.

**Comment by MilanMaurice** [comment] 2015-05-22 08:36
+1!

**Comment by kayvink** [comment] 2015-05-22 09:16
+1

**Comment by danamajid** [comment] 2015-05-22 10:26
+1

**Comment by TAKeanice** [comment] 2015-05-22 12:00
Please stop commenting "+1" which is of no use for anybody. Can you provide some details about the line of code where you are calling this method?

**Comment by TAKeanice** [comment] 2015-05-22 12:02
Some devices means which ones specifically? Any hint about the operating system, the device class (which should not make a difference), other circumstances that could make it easier for me to reproduce the issue?

**Comment by TAKeanice** [comment] 2015-05-22 12:13
One additional question: Are you dispatching the access to the same queue every time? Not doing so could result in accessing the address book from different threads, which is forbidden.

**Comment by samuelbeek** [comment] 2015-05-22 16:07
Ah, that's it! I didn't know that you could only access it in one que. Thanks :)

**Comment by TAKeanice** [comment] 2015-05-22 16:21
Yes. If you want, you could as well engineer a fix _inside_ SwiftAddressBookWrapper and/or the other classes and make a pull request. Then we could add "Thread safe" to the feature list ;)
For instance, we could stop saving the reference and re-create the ABAddressbook every time. The performance implications and the issues with the pointers have to be explored then.
Otherwise, we could actually try to create one dedicated thread. It won´t work with GCD, because it does not guarantee the same thread every time.
Maybe, locking the SwiftAddressBook object on every access would be sufficient, too.
See http://stackoverflow.com/questions/7013411/why-would-abaddressbookref-need-to-be-created-for-each-thread for some ideas

**Comment by TAKeanice** [comment] 2015-05-25 06:48
So is it working now?  Then please close the issue, @samuelbeek

**Comment by samuelbeek** [comment] 2015-05-25 16:02
Yes I'm working on a version which I will submit a pull request for.

**Closed** 2015-05-25 16:03 UTC

**Comment by TAKeanice** [comment] 2015-05-27 08:01
Cool! Thank you very much.
